In [3]:
import numpy as np
np.__version__   #to check the version we pass this attribute if it is in braket we say it as function

'1.16.2'

In [4]:
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
a=np.array([[1,2,3],(4,5,6)])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [9]:
a=np.array([(1,2,3,4),(4,5,6)]) #unequal number in data will end up with wrong output 
print(a)
print(a.ndim)

[(1, 2, 3, 4) (4, 5, 6)]
1


In [12]:
a,b=np.ones((2,3,4))
print(a,"\n")
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
list1=[]
a=1
while(a<=5):
    value=int(input("enter number for a"))
    list1.append(value)
    a+=1
print(list1)
list2=[]
b=1
while(b<=5):
    value=int(input("enter number for a"))
    list2.append(value)
    b+=1
print(list2)
c=np.array(list1,list2)
print(c)

enter number for a1
enter number for a2
enter number for a3
enter number for a4
enter number for a5
[1, 2, 3, 4, 5]
enter number for a1
enter number for a2
enter number for a34
enter number for a4
enter number for a5
[1, 2, 34, 4, 5]


TypeError: data type not understood

In [27]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
# Initialize matrix 
matrix = [] 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[] 
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print() 

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
1
2
3
4
1 2 
3 4 


In [21]:
a,b=np.zeros((2,3,4), dtype=np.int)
print(a,"\n")
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
c,d=np.full((2,2,2),5)
print(c,"\n")
print(d)

[[5 5]
 [5 5]] 

[[5 5]
 [5 5]]


In [22]:
a=np.identity(3,dtype=np.int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
a=np.random.random((5,2))    #1st random to call the package and 2nd to call the function
print(a)

a=np.random.random_integers(50,100,(3,4))
print(a)

[[0.34183225 0.6220025 ]
 [0.13503649 0.83881436]
 [0.26013591 0.67383479]
 [0.46812012 0.53471965]
 [0.93964941 0.98323928]]
[[83 65 84 51]
 [73 76 54 98]
 [66 62 80 94]]


C:\Users\Mamta\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: This function is deprecated. Please call randint(50, 100 + 1) instead
  after removing the cwd from sys.path.


In [33]:
a=np.array([(1,2,3,4),(4,5,6,7)])
print(a)
print(a.size)
print(a.shape)

[[1 2 3 4]
 [4 5 6 7]]
8
(2, 4)


In [35]:
a=np.resize(a,(6,3))
print(a,"\n")
a=np.reshape(a,(2,9))  #it will only chnge the shape it will not repeate the element to reache the specified value
                        #for eg if i have 3*4=12 element then to reshape should also contain the same no. of element
                        #we wont modify the data in reshape..""we modify the data by resize""
print(a)

[[1 2 3]
 [4 4 5]
 [6 7 1]
 [2 3 4]
 [4 5 6]
 [7 1 2]] 

[[1 2 3 4 4 5 6 7 1]
 [2 3 4 4 5 6 7 1 2]]


In [41]:
#Indexing and slicing

a=np.array([(1,2,3,4),(3,4,5,6),(8,9,10,11)])
print(a)
print(a[0,2])
print(a[:,2])
print()
print(a[0:2,0:3])



[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
3
[ 3  5 10]

[[1 2 3]
 [3 4 5]]


In [52]:
a=np.linspace(1,14,6)  #(1,14 is range dividing it in 6 equal parts)
print(a)
a=np.arange(0,24,2)    # (0,25 range start from zero and it will exclide the last value i.e 24 and it will increment
                                        #the value by specific interval)
print(a)

a=np.arange(100,69,-2)
print(a)

[ 1.   3.6  6.2  8.8 11.4 14. ]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70]


In [56]:
#aggregate functon
a=np.array([(8,9),(10,11),(12,13)])
print(len(a)) #it will only give us the number of tuples not the number of values present in tuple
print(a.size)
print(a.min())
print(a.max())
print(a.sum())
print(a.sum()/a.size)
print(a.mean)

3
6
8
13
63
10.5
<built-in method mean of numpy.ndarray object at 0x0000018872D1A850>


In [59]:
a=np.array([(1,0,3),(3,4,5)])
print(np.sqrt(a),"\n")
print(np.std(a),"\n")
print(np.log(a),"\n")
b=np.sqrt(a)
print(b.round(2))

[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]] 

1.699673171197595 

[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]] 

[[1.   0.   1.73]
 [1.73 2.   2.24]]


C:\Users\Mamta\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [ ]:
##ARRAY PROCESSING FUNCTION


In [5]:
x=np.array([(1,2),(3,4)])
y=np.array([(5,6),(3,4)])
print(x, "\n")
print(y,"\n")
print(x+y,"\n")
print(x-y,"\n")
print(x*y,"\n")
print(x/y,"\n")
print(x%y,"\n")
print(x@y,"\n")  #dot matrix multiplication
print(np.dot(x,y))


#np.add(), np.suntract()  ,np.multiply(),    np.divide(),   np.remainder()

[[1 2]
 [3 4]] 

[[5 6]
 [3 4]] 

[[6 8]
 [6 8]] 

[[-4 -4]
 [ 0  0]] 

[[ 5 12]
 [ 9 16]] 

[[0.2        0.33333333]
 [1.         1.        ]] 

[[1 2]
 [0 0]] 

[[11 14]
 [27 34]] 

[[11 14]
 [27 34]]


In [ ]:
#   ""HELP""
import numpy as np
#?np.mean
print(np.lookfor("mean"))
help(np.zeros)


In [12]:
#joining array

print(x)
print(y,"\n")
d=np.concatenate((x,y),axis=0)   #0=row wise   1=column wise
print(d,"\n")
print(np.vstack((x,y)))   #can not perform when we have unequal number of elements in array
print("\n")
print(np.hstack((x,y)))   #similar array is require

[[1 2]
 [3 4]]
[[5 6]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]
 [3 4]]


[[1 2 5 6]
 [3 4 3 4]]


In [15]:
#converting array in single row
print(x)
z=x.ravel()
print()
print(z,"\n")
print(z.reshape(2,2))

[[1 2]
 [3 4]]

[1 2 3 4] 

[[1 2]
 [3 4]]


In [16]:
#APPEND FUNCTION  is used when we want to join to matrix which h different no odf values like 2*2 and 3*3
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(6,7),(9,10)])    #ravel work in backend it flatend the array
new_array=np.append(x,y)
print(new_array)
new_array=np.reshape(new_array,(5,2))
print(new_array)

[ 1  2  3  3  4  5  6  7  9 10]
[[ 1  2]
 [ 3  3]
 [ 4  5]
 [ 6  7]
 [ 9 10]]


In [18]:
x=np.array([(1,2,3),(3,4,5)])
                        #here ravel function 1st execute at backend

print(x)
new_array=np.insert(x,[1,3],5)
print(new_array)


[[1 2 3]
 [3 4 5]]
[1 5 2 3 5 3 4 5]


In [19]:
new_array=np.delete(new_array,[1,2])
print(new_array)

[1 3 5 3 4 5]


In [24]:
x=np.array([(1,2,3),(3,4,5)])
x[0,1]=7    #replacing the value
print(x)

[[1 7 3]
 [3 4 5]]


In [26]:
my_array2=np.genfromtxt(r"D:\MAMTA\Data Set\python\sample.txt",
                        skip_header=1,delimiter=",",
                      filling_values=0,unpack= True,dtype=np.int)
                        #filling=0 for fill the missing value as 0 
                        #unpack= to arrange data row or column wise it transpose the matrix
        
print(my_array2)           


[[1 4 7]
 [2 0 8]
 [3 6 9]]
