In [1]:
"""Attribute Information:

To construct the data, seven geometric parameters of wheat kernels were measured: 
1. area A, 
2. perimeter P, 
3. compactness C = 4*pi*A/P^2, 
4. length of kernel, 
5. width of kernel, 
6. asymmetry coefficient 
7. length of kernel groove. 
All of these parameters were real-valued continuous"""

'Attribute Information:\n\nTo construct the data, seven geometric parameters of wheat kernels were measured: \n1. area A, \n2. perimeter P, \n3. compactness C = 4*pi*A/P^2, \n4. length of kernel, \n5. width of kernel, \n6. asymmetry coefficient \n7. length of kernel groove. \nAll of these parameters were real-valued continuous'

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('seeds_dataset.txt' , sep='\t',header=None,names=['area','perimeter','compactness',
                                                                 'length','width','coefficient','groove','class'])

In [4]:
df.head()

area  perimeter  compactness  length  width  coefficient  groove  class
0  15.26      14.84       0.8710   5.763  3.312        2.221   5.220    1.0
1  14.88      14.57       0.8811   5.554  3.333        1.018   4.956    1.0
2  14.29      14.09       0.9050   5.291  3.337        2.699   4.825    1.0
3  13.84      13.94       0.8955   5.324  3.379        2.259   4.805    1.0
4  16.14      14.99       0.9034   5.658  3.562        1.355   5.175    1.0

In [5]:
df.isnull().sum()

area           0
perimeter      0
compactness    3
length         0
width          1
coefficient    0
groove         4
class          4
dtype: int64

In [6]:
dataset=pd.DataFrame.copy(df)

In [7]:
dataset.isnull().sum()

area           0
perimeter      0
compactness    3
length         0
width          1
coefficient    0
groove         4
class          4
dtype: int64

In [8]:
dataset.dtypes

area           float64
perimeter      float64
compactness    float64
length         float64
width          float64
coefficient    float64
groove         float64
class          float64
dtype: object

In [9]:
for x in df.columns[:]:
    if df[x].dtype=='float64':
        df[x].fillna(df[x].mean(),inplace=True)

In [10]:
df.isnull().sum()

area           0
perimeter      0
compactness    0
length         0
width          0
coefficient    0
groove         0
class          0
dtype: int64

In [87]:
df=df.dropna(how='any')

In [88]:
df.shape

(199, 8)

In [89]:
df.shape

(199, 8)

In [90]:
X=df.iloc[:,0:-1].values

In [91]:
X

array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
       [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
       [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
       [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
       [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]])

In [92]:
X.shape

(199, 7)

In [93]:
Y=df.iloc[:,-1].values

In [94]:
Y.shape

(199,)

In [95]:
Y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [96]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.30,random_state=120)

In [97]:
X_train.shape

(139, 7)

In [98]:
X_test.shape

(60, 7)

In [99]:
Y_train.shape

(139,)

In [100]:
from sklearn.linear_model import LogisticRegression


In [101]:
lr=LogisticRegression()


In [102]:
lr.fit(X_train,Y_train)

C:\Users\Mamta\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Mamta\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [103]:
Y_pred=lr.predict(X_test)

In [104]:
Y_pred

array([2., 2., 2., 3., 1., 2., 2., 3., 1., 1., 2., 2., 3., 3., 3., 1., 2.,
       3., 1., 1., 1., 3., 2., 1., 2., 2., 2., 2., 3., 1., 2., 2., 2., 2.,
       3., 2., 2., 1., 1., 1., 2., 2., 1., 3., 1., 3., 1., 2., 3., 2., 2.,
       2., 3., 1., 2., 3., 3., 1., 1., 1.])

In [105]:
Y_test

array([2., 2., 2., 3., 1., 2., 2., 3., 1., 3., 1., 2., 3., 3., 3., 1., 2.,
       3., 1., 1., 1., 3., 1., 1., 2., 2., 2., 2., 3., 1., 2., 2., 2., 2.,
       3., 1., 2., 1., 1., 1., 2., 2., 1., 3., 1., 3., 1., 1., 3., 2., 2.,
       2., 3., 1., 2., 3., 1., 1., 3., 1.])

In [74]:
from sklearn.metrics import confusion_matrix

In [106]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[17  4  1]
 [ 0 22  0]
 [ 2  0 14]]
0.8833333333333333
              precision    recall  f1-score   support

         1.0       0.89      0.77      0.83        22
         2.0       0.85      1.00      0.92        22
         3.0       0.93      0.88      0.90        16

   micro avg       0.88      0.88      0.88        60
   macro avg       0.89      0.88      0.88        60
weighted avg       0.89      0.88      0.88        60



In [1]:
from sklearn import metrics

fpr, tpr,z = metrics.roc_curve(Y_test, y_pred_class)
auc = metrics.auc(fpr,tpr)
print(auc)
print(fpr)
print(tpr)
print(z)

NameError: name 'Y_test' is not defined

In [ ]:
import matplotlib.pyplot as plt
#%matplotlib inline                    
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, 'b', label = auc)
plt.legend(loc = 'lower right')
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.show()